### ISSUE TITLE
Call for code

### ISSUE THREAD

**Issue by Radium98** [bing-li-ai/AniGAN#1]
Can you upload your code ASAP？

**Comment by summerice9** [comment]
Thanks for your interest. 

Our paper is in under-review status. We will consider releasing  our code, after our paper is accepted.

**Comment by bing-li-ai** [comment]
Thanks for your interest.

Our paper is in under-review status. We will consider releasing our code, after our paper is accepted.

**Comment by qcy007** [comment]
> Thanks for your interest.
> 
> Our paper is in under-review status. We will consider releasing our code, after our paper is accepted.

A wonderful project，wish the paper to be accepted smoothly.

**Comment by bing-li-ai** [comment]
> > Thanks for your interest.
> > Our paper is in under-review status. We will consider releasing our code, after our paper is accepted.
> 
> A wonderful project，wish the paper to be accepted smoothly.

Thank you so much for your kind words

**Comment by trantuanngoc** [comment]
@bing-li-ai the paper is already published, can you publish the code or send me privately. I really appricate it

**Comment by bing-li-ai** [comment]
Hi, we have released the inference code

**Comment by yl-zhu** [comment]
> @bing-li-ai the paper is already published, can you publish the code or send me privately (Non-Commercial Use), i really need it. I really appricate it

Hi, this code borrows heavily from https://github.com/NVlabs/FUNIT. For training details, replacing our generator and discriminator with FUNIT will significantly improve the effect.

**Comment by yl-zhu** [comment]
> @bing-li-ai the paper is already published, can you publish the code or send me privately (Non-Commercial Use), i really need it. I really appricate it

Hi, this code borrows heavily from https://github.com/NVlabs/FUNIT. For training details, replacing FUNIT G and D with AniGAN will significantly improve the effect.

**Comment by trantuanngoc** [comment]
> Hi, we have released the inference code

Could you provide the training code? It's kind of confused when imagine how model look with poor code.

**Comment by bing-li-ai** [comment]
> > Hi, we have released the inference code
> 
> Could you provide the training code? It's kind of confused when imagine how model look with poor code.
Hi, @trantuanngoc 
Our training code is based on https://github.com/NVlabs/FUNIT. Replacing FUNIT G and D with AniGAN will significantly improve the effect.
