### ISSUE TITLE
Question regarding the encoders

### ISSUE THREAD

**Issue by jis478** [bing-li-ai/AniGAN#2]
Hi, thanks for the awesome paper. I have some questions regarding the networks in the paper.

Is there only a single generator covering both domain A and B? How is it supposed to generate both domains' features? (For discriminator it has two branches so it makes sense.)

Thanks,

**Comment by summerice9** [comment]
Many thanks for  your interest.

Yes,  the weights of  the generator are shared between  A-->B and B--> A.   According to our observation, such single generator can generate high-quality results,  if  loss functions are properly designed.  Many recent works such as FUNIT and stargan also only use single generator for two/multiple domains.

**Comment by bing-li-ai** [comment]
Many thanks for your interest.

Yes, the weights of the generator are shared between A-->B and B--> A. According to our observation, such single generator can generate high-quality results, if loss functions are properly designed. Many recent works such as FUNIT and stargan also only use single generator for two/multiple domains.

**Comment by jis478** [comment]
Hi, I've tried to implement according to your paper but no success. Would you please have a loot at my codes (https://github.com/jis478/AniGAN) and give me some directions on improving the results?
