### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by Gutianpei** [bing-li-ai/AniGAN#3]
Hello Bing,

Thanks for the amazing work! I'm trying to reproduce the work and my implementation generates some weird outputs, could you provide the email address that I can reach out to you? Thank you very much!

**Comment by jis478** [comment]
I'm also trying to reproduce the results but the quality never comes to the one in the paper. Would you also share with me as well?

**Comment by Gutianpei** [comment]
> I'm also trying to reproduce the results but the quality never comes near to the ones in the paper. Would you also share with me your contact info?

Hello Mark,

Are you able to get a plausible result or just random noise? In my case the generator only produces random noise and the model seems collapsed, but I followed all the configurations as the paper.

**Comment by jis478** [comment]
> > I'm also trying to reproduce the results but the quality never comes near to the ones in the paper. Would you also share with me your contact info?
> 
> Hello Mark,
> 
> Are you able to get a plausible result or just random noise? In my case the generator only produces random noise and the model seems collapsed, but I followed all the configurations as the paper.

You can check out my repo (https://github.com/jis478/AniGAN). I've reproduced many of detail points in the paper but still no luck.

**Comment by Gutianpei** [comment]
> > > I'm also trying to reproduce the results but the quality never comes near to the ones in the paper. Would you also share with me your contact info?
> > 
> > 
> > Hello Mark,
> > Are you able to get a plausible result or just random noise? In my case the generator only produces random noise and the model seems collapsed, but I followed all the configurations as the paper.
> 
> You can check out my repo (https://github.com/jis478/AniGAN). I've reproduced many of detail points in the paper but still no luck.

Hello Mark,

My latest experiment finally shows a preliminary success. Here are some points I can think of from a glance at your code.
1. You might want to use nn.BCEWithLogitsLoss() for adv loss and be careful that G and D have opposite sign.
2. FST block is an upsampling block. In my case I did not implement an extra decoder and the FST serves as a decoder

The above suggestions are not guaranteed to be correct, and I hope that helps. Good luck!

**Comment by jis478** [comment]
> > > > I'm also trying to reproduce the results but the quality never comes near to the ones in the paper. Would you also share with me your contact info?
> > > 
> > > 
> > > Hello Mark,
> > > Are you able to get a plausible result or just random noise? In my case the generator only produces random noise and the model seems collapsed, but I followed all the configurations as the paper.
> > 
> > 
> > You can check out my repo (https://github.com/jis478/AniGAN). I've reproduced many of detail points in the paper but still no luck.
> 
> Hello Mark,
> 
> My latest experiment finally shows a preliminary success. Here are some points I can think of from a glance at your code.
> 
> 1. You might want to use nn.BCEWithLogitsLoss() for adv loss and be careful that G and D have opposite sign.
> 2. FST block is an upsampling block. In my case I did not implement an extra decoder and the FST serves as a decoder
> 
> The above suggestions are not guaranteed to be correct, and I hope that helps. Good luck!

Hi, thanks for the tips! Actually I've also used FST block(s) as a decoder so there shouldn't be much difference. Would you allow me to have a look at your code?
