### ISSUE TITLE
About the code of training loop

### ISSUE THREAD

**Issue by silence-tang** [bing-li-ai/AniGAN#5]
Dear authors:
    Could you please share the code of your training loop? It will help me l lot because I am doing my graduation project. 
    Thanks a lot!

**Comment by bing-li-ai** [comment]
> 



> Dear authors: Could you please share the code of your training loop? It will help me l lot because I am doing my graduation project. Thanks a lot!

Our training code is based on https://github.com/NVlabs/FUNIT. Replacing FUNIT G and D with AniGAN will significantly improve the effect.
